// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#include "NativeResamplingAudioChannel.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeResamplingAudioChannel::NativeResamplingAudioChannel() : ::djinni::JniInterface<::nok::ResamplingAudioChannel, NativeResamplingAudioChannel>("co/zenturi/nok/ResamplingAudioChannel$CppProxy") {}

NativeResamplingAudioChannel::~NativeResamplingAudioChannel() = default;


CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::nok::ResamplingAudioChannel>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1getData(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        auto r = ref->get_data();
        return ::djinni::release(::djinni::List<::djinni::F32>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1setData(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_d)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->set_data(::djinni::List<::djinni::F32>::toCpp(jniEnv, j_d));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1getSamplesRate(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        auto r = ref->get_samplesRate();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_create(JNIEnv* jniEnv, jobject /*this*/, jboolean j_looping, jint j_sampleRate)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::nok::ResamplingAudioChannel::create(::djinni::Bool::toCpp(jniEnv, j_looping),
                                                       ::djinni::I32::toCpp(jniEnv, j_sampleRate));
        return ::djinni::release(::djinni_generated::NativeResamplingAudioChannel::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jfloat JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1sample(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_position, jint j_sampleRate)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        auto r = ref->sample(::djinni::I32::toCpp(jniEnv, j_position),
                             ::djinni::I32::toCpp(jniEnv, j_sampleRate));
        return ::djinni::release(::djinni::F32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1lerp(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jfloat j_v0, jfloat j_v1, jfloat j_t)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->lerp(::djinni::F32::toCpp(jniEnv, j_v0),
                  ::djinni::F32::toCpp(jniEnv, j_v1),
                  ::djinni::F32::toCpp(jniEnv, j_t));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1sampleLength(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_sampleRate)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        auto r = ref->sampleLength(::djinni::I32::toCpp(jniEnv, j_sampleRate));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1nextSamples(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_requestedSamples, jint j_requestedLength, jint j_sampleRate)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->nextSamples(::djinni::List<::djinni::F32>::toCpp(jniEnv, j_requestedSamples),
                         ::djinni::I32::toCpp(jniEnv, j_requestedLength),
                         ::djinni::I32::toCpp(jniEnv, j_sampleRate));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1play(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->play();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1pause(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->pause();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1stop(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->stop();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jfloat JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1getLength(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        auto r = ref->get_length();
        return ::djinni::release(::djinni::F32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jfloat JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1getPosition(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        auto r = ref->get_position();
        return ::djinni::release(::djinni::F32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1setPosition(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jfloat j_pos)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->set_position(::djinni::F32::toCpp(jniEnv, j_pos));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jfloat JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1getVolume(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        auto r = ref->get_volume();
        return ::djinni::release(::djinni::F32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1setVolume(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jfloat j_vol)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->set_volume(::djinni::F32::toCpp(jniEnv, j_vol));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jboolean JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1getFinished(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        auto r = ref->get_finished();
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1max(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_a, jint j_b)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->max(::djinni::I32::toCpp(jniEnv, j_a),
                 ::djinni::I32::toCpp(jniEnv, j_b));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_ResamplingAudioChannel_00024CppProxy_native_1min(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_a, jint j_b)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::ResamplingAudioChannel>(nativeRef);
        ref->min(::djinni::I32::toCpp(jniEnv, j_a),
                 ::djinni::I32::toCpp(jniEnv, j_b));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
