// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#include "NativeTexture.hpp"  // my header
#include "Marshal.hpp"
#include "NativeImageCompression.hpp"
#include "NativeImageFormat.hpp"
#include "NativeTextureUnit.hpp"

namespace djinni_generated {

NativeTexture::NativeTexture() : ::djinni::JniInterface<::nok::Texture, NativeTexture>("co/zenturi/nok/Texture$CppProxy") {}

NativeTexture::~NativeTexture() = default;


CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::nok::Texture>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_create(JNIEnv* jniEnv, jobject /*this*/, jint j_width, jint j_height, jobject j_format, jboolean j_readable)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::nok::Texture::create(::djinni::I32::toCpp(jniEnv, j_width),
                                        ::djinni::I32::toCpp(jniEnv, j_height),
                                        ::djinni_generated::NativeImageFormat::toCpp(jniEnv, j_format),
                                        ::djinni::Bool::toCpp(jniEnv, j_readable));
        return ::djinni::release(::djinni_generated::NativeTexture::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_create3D(JNIEnv* jniEnv, jobject /*this*/, jint j_width, jint j_height, jint j_depth, jobject j_format, jboolean j_readable)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::nok::Texture::create3D(::djinni::I32::toCpp(jniEnv, j_width),
                                          ::djinni::I32::toCpp(jniEnv, j_height),
                                          ::djinni::I32::toCpp(jniEnv, j_depth),
                                          ::djinni_generated::NativeImageFormat::toCpp(jniEnv, j_format),
                                          ::djinni::Bool::toCpp(jniEnv, j_readable));
        return ::djinni::release(::djinni_generated::NativeTexture::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_fromData(JNIEnv* jniEnv, jobject /*this*/, jbyteArray j_data, jint j_width, jint j_height, jobject j_format, jboolean j_readable)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::nok::Texture::fromData(::djinni::Binary::toCpp(jniEnv, j_data),
                                          ::djinni::I32::toCpp(jniEnv, j_width),
                                          ::djinni::I32::toCpp(jniEnv, j_height),
                                          ::djinni_generated::NativeImageFormat::toCpp(jniEnv, j_format),
                                          ::djinni::Bool::toCpp(jniEnv, j_readable));
        return ::djinni::release(::djinni_generated::NativeTexture::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_fromData3D(JNIEnv* jniEnv, jobject /*this*/, jbyteArray j_data, jint j_width, jint j_height, jint j_depth, jobject j_format, jboolean j_readable)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::nok::Texture::fromData3D(::djinni::Binary::toCpp(jniEnv, j_data),
                                            ::djinni::I32::toCpp(jniEnv, j_width),
                                            ::djinni::I32::toCpp(jniEnv, j_height),
                                            ::djinni::I32::toCpp(jniEnv, j_depth),
                                            ::djinni_generated::NativeImageFormat::toCpp(jniEnv, j_format),
                                            ::djinni::Bool::toCpp(jniEnv, j_readable));
        return ::djinni::release(::djinni_generated::NativeTexture::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1Set(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_unit)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->_set(::djinni_generated::NativeTextureUnit::toCpp(jniEnv, j_unit));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1SetImage(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_unit)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->_setImage(::djinni_generated::NativeTextureUnit::toCpp(jniEnv, j_unit));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jbyteArray JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1lock(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->lock();
        return ::djinni::release(::djinni::Binary::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1unlock(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->unlock();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1clear(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_x, jint j_y, jint j_z, jint j_width, jint j_height, jint j_depth, jint j_color)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->clear(::djinni::I32::toCpp(jniEnv, j_x),
                   ::djinni::I32::toCpp(jniEnv, j_y),
                   ::djinni::I32::toCpp(jniEnv, j_z),
                   ::djinni::I32::toCpp(jniEnv, j_width),
                   ::djinni::I32::toCpp(jniEnv, j_height),
                   ::djinni::I32::toCpp(jniEnv, j_depth),
                   ::djinni::I32::toCpp(jniEnv, j_color));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1upload(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jbyteArray j_data, jint j_stride)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->upload(::djinni::Binary::toCpp(jniEnv, j_data),
                    ::djinni::I32::toCpp(jniEnv, j_stride));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1generateMipmaps(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_levels)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->generateMipmaps(::djinni::I32::toCpp(jniEnv, j_levels));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1setMipMap(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_mipmap, jint j_level)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->setMipMap(::djinni_generated::NativeTexture::toCpp(jniEnv, j_mipmap),
                       ::djinni::I32::toCpp(jniEnv, j_level));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1stride(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->stride();
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getTexHeight(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_texHeight();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getTexWidth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_texWidth();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1setTexWidth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_width)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->set_texWidth(::djinni::I32::toCpp(jniEnv, j_width));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1setTexHeight(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_height)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->set_texHeight(::djinni::I32::toCpp(jniEnv, j_height));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getTexDepth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_texDepth();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1setTexDepth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_depth)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->set_texDepth(::djinni::I32::toCpp(jniEnv, j_depth));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1at(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_x, jint j_y)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->at(::djinni::I32::toCpp(jniEnv, j_x),
                         ::djinni::I32::toCpp(jniEnv, j_y));
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jbyteArray JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getPixels(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->getPixels();
        return ::djinni::release(::djinni::Binary::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getFormat(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_format();
        return ::djinni::release(::djinni_generated::NativeImageFormat::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1readable(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->readable();
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getCompression(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_compression();
        return ::djinni::release(::djinni_generated::NativeImageCompression::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jbyteArray JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getData(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_data();
        return ::djinni::release(::djinni::Binary::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getDataSize(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_dataSize();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getHeight(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_height();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getWidth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_width();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1setWidth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_width)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->set_width(::djinni::I32::toCpp(jniEnv, j_width));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1setHeight(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_height)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->set_height(::djinni::I32::toCpp(jniEnv, j_height));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jint JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1getDepth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        auto r = ref->get_depth();
        return ::djinni::release(::djinni::I32::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_co_zenturi_nok_Texture_00024CppProxy_native_1setDepth(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_depth)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::nok::Texture>(nativeRef);
        ref->set_depth(::djinni::I32::toCpp(jniEnv, j_depth));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

}  // namespace djinni_generated
