// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#pragma once

#include "audio1.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAudio1 final : ::djinni::JniInterface<::nok::Audio1, NativeAudio1> {
public:
    using CppType = std::shared_ptr<::nok::Audio1>;
    using CppOptType = std::shared_ptr<::nok::Audio1>;
    using JniType = jobject;

    using Boxed = NativeAudio1;

    ~NativeAudio1();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeAudio1>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeAudio1>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeAudio1();
    friend ::djinni::JniClass<NativeAudio1>;
    friend ::djinni::JniInterface<::nok::Audio1, NativeAudio1>;

};

}  // namespace djinni_generated
