// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "vertex_buffer.hpp"

namespace djinni_generated {

class NativeVertexBuffer final : ::djinni::JniInterface<::nok::VertexBuffer, NativeVertexBuffer> {
public:
    using CppType = std::shared_ptr<::nok::VertexBuffer>;
    using CppOptType = std::shared_ptr<::nok::VertexBuffer>;
    using JniType = jobject;

    using Boxed = NativeVertexBuffer;

    ~NativeVertexBuffer();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVertexBuffer>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVertexBuffer>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVertexBuffer();
    friend ::djinni::JniClass<NativeVertexBuffer>;
    friend ::djinni::JniInterface<::nok::VertexBuffer, NativeVertexBuffer>;

};

}  // namespace djinni_generated
