// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#pragma once

#include "djinni_support.hpp"
#include "vec3_module.hpp"

namespace djinni_generated {

class NativeVec3Module final : ::djinni::JniInterface<::nok::Vec3Module, NativeVec3Module> {
public:
    using CppType = std::shared_ptr<::nok::Vec3Module>;
    using CppOptType = std::shared_ptr<::nok::Vec3Module>;
    using JniType = jobject;

    using Boxed = NativeVec3Module;

    ~NativeVec3Module();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVec3Module>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVec3Module>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVec3Module();
    friend ::djinni::JniClass<NativeVec3Module>;
    friend ::djinni::JniInterface<::nok::Vec3Module, NativeVec3Module>;

};

}  // namespace djinni_generated
