// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "vertex_data.hpp"

namespace djinni_generated {

class NativeVertexData final : ::djinni::JniEnum {
public:
    using CppType = ::nok::VertexData;
    using JniType = jobject;

    using Boxed = NativeVertexData;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeVertexData>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeVertexData>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeVertexData() : JniEnum("co/zenturi/nok/VertexData") {}
    friend ::djinni::JniClass<NativeVertexData>;
};

}  // namespace djinni_generated
