// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "vertex_element.hpp"

namespace djinni_generated {

class NativeVertexElement final : ::djinni::JniInterface<::nok::VertexElement, NativeVertexElement> {
public:
    using CppType = std::shared_ptr<::nok::VertexElement>;
    using CppOptType = std::shared_ptr<::nok::VertexElement>;
    using JniType = jobject;

    using Boxed = NativeVertexElement;

    ~NativeVertexElement();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVertexElement>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVertexElement>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVertexElement();
    friend ::djinni::JniClass<NativeVertexElement>;
    friend ::djinni::JniInterface<::nok::VertexElement, NativeVertexElement>;

};

}  // namespace djinni_generated
