// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "texture_filter.hpp"

namespace djinni_generated {

class NativeTextureFilter final : ::djinni::JniEnum {
public:
    using CppType = ::nok::TextureFilter;
    using JniType = jobject;

    using Boxed = NativeTextureFilter;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeTextureFilter>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeTextureFilter>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeTextureFilter() : JniEnum("co/zenturi/nok/TextureFilter") {}
    friend ::djinni::JniClass<NativeTextureFilter>;
};

}  // namespace djinni_generated
