// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "shader_type.hpp"

namespace djinni_generated {

class NativeShaderType final : ::djinni::JniEnum {
public:
    using CppType = ::nok::ShaderType;
    using JniType = jobject;

    using Boxed = NativeShaderType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeShaderType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeShaderType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeShaderType() : JniEnum("co/zenturi/nok/ShaderType") {}
    friend ::djinni::JniClass<NativeShaderType>;
};

}  // namespace djinni_generated
