// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#include "NativeBakedChar.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeBakedChar::NativeBakedChar() = default;

NativeBakedChar::~NativeBakedChar() = default;

auto NativeBakedChar::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeBakedChar>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.x0)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.y0)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.x1)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.x2)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.xoff)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.yoff)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.xadvance)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeBakedChar::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 8);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeBakedChar>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mX0)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mY0)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mX1)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mX2)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mXoff)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mYoff)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mXadvance))};
}

}  // namespace djinni_generated
