// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "aligned_quad.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAlignedQuad final {
public:
    using CppType = ::nok::AlignedQuad;
    using JniType = jobject;

    using Boxed = NativeAlignedQuad;

    ~NativeAlignedQuad();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeAlignedQuad();
    friend ::djinni::JniClass<NativeAlignedQuad>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("co/zenturi/nok/AlignedQuad") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(FFFFFFFFF)V") };
    const jfieldID field_mX0 { ::djinni::jniGetFieldID(clazz.get(), "mX0", "F") };
    const jfieldID field_mY0 { ::djinni::jniGetFieldID(clazz.get(), "mY0", "F") };
    const jfieldID field_mS0 { ::djinni::jniGetFieldID(clazz.get(), "mS0", "F") };
    const jfieldID field_mT0 { ::djinni::jniGetFieldID(clazz.get(), "mT0", "F") };
    const jfieldID field_mX1 { ::djinni::jniGetFieldID(clazz.get(), "mX1", "F") };
    const jfieldID field_mY1 { ::djinni::jniGetFieldID(clazz.get(), "mY1", "F") };
    const jfieldID field_mS1 { ::djinni::jniGetFieldID(clazz.get(), "mS1", "F") };
    const jfieldID field_mT1 { ::djinni::jniGetFieldID(clazz.get(), "mT1", "F") };
    const jfieldID field_mXadvance { ::djinni::jniGetFieldID(clazz.get(), "mXadvance", "F") };
};

}  // namespace djinni_generated
