// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#pragma once

#include "djinni_support.hpp"
#include "mat2_module.hpp"

namespace djinni_generated {

class NativeMat2Module final : ::djinni::JniInterface<::nok::Mat2Module, NativeMat2Module> {
public:
    using CppType = std::shared_ptr<::nok::Mat2Module>;
    using CppOptType = std::shared_ptr<::nok::Mat2Module>;
    using JniType = jobject;

    using Boxed = NativeMat2Module;

    ~NativeMat2Module();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMat2Module>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMat2Module>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMat2Module();
    friend ::djinni::JniClass<NativeMat2Module>;
    friend ::djinni::JniInterface<::nok::Mat2Module, NativeMat2Module>;

};

}  // namespace djinni_generated
