// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "shader.hpp"

namespace djinni_generated {

class NativeShader final : ::djinni::JniInterface<::nok::Shader, NativeShader> {
public:
    using CppType = std::shared_ptr<::nok::Shader>;
    using CppOptType = std::shared_ptr<::nok::Shader>;
    using JniType = jobject;

    using Boxed = NativeShader;

    ~NativeShader();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeShader>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeShader>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeShader();
    friend ::djinni::JniClass<NativeShader>;
    friend ::djinni::JniInterface<::nok::Shader, NativeShader>;

};

}  // namespace djinni_generated
