// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "texture.hpp"

namespace djinni_generated {

class NativeTexture final : ::djinni::JniInterface<::nok::Texture, NativeTexture> {
public:
    using CppType = std::shared_ptr<::nok::Texture>;
    using CppOptType = std::shared_ptr<::nok::Texture>;
    using JniType = jobject;

    using Boxed = NativeTexture;

    ~NativeTexture();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTexture>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTexture>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTexture();
    friend ::djinni::JniClass<NativeTexture>;
    friend ::djinni::JniInterface<::nok::Texture, NativeTexture>;

};

}  // namespace djinni_generated
