// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#pragma once

#include "djinni_support.hpp"
#include "resampling_audio_channel.hpp"

namespace djinni_generated {

class NativeResamplingAudioChannel final : ::djinni::JniInterface<::nok::ResamplingAudioChannel, NativeResamplingAudioChannel> {
public:
    using CppType = std::shared_ptr<::nok::ResamplingAudioChannel>;
    using CppOptType = std::shared_ptr<::nok::ResamplingAudioChannel>;
    using JniType = jobject;

    using Boxed = NativeResamplingAudioChannel;

    ~NativeResamplingAudioChannel();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeResamplingAudioChannel>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeResamplingAudioChannel>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeResamplingAudioChannel();
    friend ::djinni::JniClass<NativeResamplingAudioChannel>;
    friend ::djinni::JniInterface<::nok::ResamplingAudioChannel, NativeResamplingAudioChannel>;

};

}  // namespace djinni_generated
