// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "graphics.hpp"

namespace djinni_generated {

class NativeGraphics final : ::djinni::JniInterface<::nok::Graphics, NativeGraphics> {
public:
    using CppType = std::shared_ptr<::nok::Graphics>;
    using CppOptType = std::shared_ptr<::nok::Graphics>;
    using JniType = jobject;

    using Boxed = NativeGraphics;

    ~NativeGraphics();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeGraphics>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeGraphics>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeGraphics();
    friend ::djinni::JniClass<NativeGraphics>;
    friend ::djinni::JniInterface<::nok::Graphics, NativeGraphics>;

};

}  // namespace djinni_generated
