// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "texture_array.hpp"

namespace djinni_generated {

class NativeTextureArray final : ::djinni::JniInterface<::nok::TextureArray, NativeTextureArray> {
public:
    using CppType = std::shared_ptr<::nok::TextureArray>;
    using CppOptType = std::shared_ptr<::nok::TextureArray>;
    using JniType = jobject;

    using Boxed = NativeTextureArray;

    ~NativeTextureArray();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeTextureArray>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeTextureArray>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeTextureArray();
    friend ::djinni::JniClass<NativeTextureArray>;
    friend ::djinni::JniInterface<::nok::TextureArray, NativeTextureArray>;

};

}  // namespace djinni_generated
