// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "djinni_support.hpp"
#include "texture_addressing.hpp"

namespace djinni_generated {

class NativeTextureAddressing final : ::djinni::JniEnum {
public:
    using CppType = ::nok::TextureAddressing;
    using JniType = jobject;

    using Boxed = NativeTextureAddressing;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeTextureAddressing>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeTextureAddressing>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeTextureAddressing() : JniEnum("co/zenturi/nok/TextureAddressing") {}
    friend ::djinni::JniClass<NativeTextureAddressing>;
};

}  // namespace djinni_generated
