// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include "constant_location.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeConstantLocation final : ::djinni::JniInterface<::nok::ConstantLocation, NativeConstantLocation> {
public:
    using CppType = std::shared_ptr<::nok::ConstantLocation>;
    using CppOptType = std::shared_ptr<::nok::ConstantLocation>;
    using JniType = jobject;

    using Boxed = NativeConstantLocation;

    ~NativeConstantLocation();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeConstantLocation>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeConstantLocation>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeConstantLocation();
    friend ::djinni::JniClass<NativeConstantLocation>;
    friend ::djinni::JniInterface<::nok::ConstantLocation, NativeConstantLocation>;

};

}  // namespace djinni_generated
