// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

package co.zenturi.nok;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Audio {
    public abstract int getSamplesPerSecond();

    public static native AudioChannel stream(Sound sound, boolean loop);

    public static native void init();

    public static native AudioBuffer getBuffer();

    public static native void setBuffer(AudioBuffer buf);

    public static native void update();

    public static native void shutdown();

    public static native float readSample();

    private static final class CppProxy extends Audio
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public int getSamplesPerSecond()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getSamplesPerSecond(this.nativeRef);
        }
        private native int native_getSamplesPerSecond(long _nativeRef);
    }
}
