// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

package co.zenturi.nok;

public final class BakedChar {


    /*package*/ final int mX0;

    /*package*/ final int mY0;

    /*package*/ final int mX1;

    /*package*/ final int mX2;

    /*package*/ final float mXoff;

    /*package*/ final float mYoff;

    /*package*/ final float mXadvance;

    public BakedChar(
            int x0,
            int y0,
            int x1,
            int x2,
            float xoff,
            float yoff,
            float xadvance) {
        this.mX0 = x0;
        this.mY0 = y0;
        this.mX1 = x1;
        this.mX2 = x2;
        this.mXoff = xoff;
        this.mYoff = yoff;
        this.mXadvance = xadvance;
    }

    public int getX0() {
        return mX0;
    }

    public int getY0() {
        return mY0;
    }

    public int getX1() {
        return mX1;
    }

    public int getX2() {
        return mX2;
    }

    public float getXoff() {
        return mXoff;
    }

    public float getYoff() {
        return mYoff;
    }

    public float getXadvance() {
        return mXadvance;
    }

    @Override
    public String toString() {
        return "BakedChar{" +
                "mX0=" + mX0 +
                "," + "mY0=" + mY0 +
                "," + "mX1=" + mX1 +
                "," + "mX2=" + mX2 +
                "," + "mXoff=" + mXoff +
                "," + "mYoff=" + mYoff +
                "," + "mXadvance=" + mXadvance +
        "}";
    }

}
