// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

package co.zenturi.nok;

public final class ConstantLocation {


    public ConstantLocation(
            ) {
    }

    @Override
    public String toString() {
        return "ConstantLocation{" +
        "}";
    }

}
