// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

package co.zenturi.nok;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class IndexBuffer {
    public abstract ArrayList<Integer> lock();

    public abstract void unlock();

    public abstract int count();

    public static IndexBuffer create(int count)
    {
        return CppProxy.create(count);
    }

    private static final class CppProxy extends IndexBuffer
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public ArrayList<Integer> lock()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_lock(this.nativeRef);
        }
        private native ArrayList<Integer> native_lock(long _nativeRef);

        @Override
        public void unlock()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_unlock(this.nativeRef);
        }
        private native void native_unlock(long _nativeRef);

        @Override
        public int count()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_count(this.nativeRef);
        }
        private native int native_count(long _nativeRef);

        public static native IndexBuffer create(int count);
    }
}
