// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

package co.zenturi.nok;

public enum TextureAddressing {
    REPEAT,
    MIRROR,
    CLAMP,
    BORDER,
    ;
}
