// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

package co.zenturi.nok;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Vec4 {
    public abstract double getX();

    public abstract double getY();

    public abstract double getZ();

    public abstract void add(Vec4 v);

    public abstract void addScaledVector(Vec4 v);

    public abstract void sub(Vec4 v);

    public abstract void multiply(double i);

    public abstract void divide(double i);

    public abstract double squareLength();

    public abstract double getLength();

    public abstract void setLength(double length);

    public abstract Vec4 normalize();

    public abstract boolean isZero();

    public abstract void set(double x, double y, double z, double w);

    public abstract double dot(Vec4 v);

    public abstract Vec4 cross(Vec4 v);

    public abstract double distance(Vec4 v);

    public abstract void invert();

    public static Vec4 create(double x, double y, double z)
    {
        return CppProxy.create(x,
                               y,
                               z);
    }

    private static final class CppProxy extends Vec4
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public double getX()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getX(this.nativeRef);
        }
        private native double native_getX(long _nativeRef);

        @Override
        public double getY()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getY(this.nativeRef);
        }
        private native double native_getY(long _nativeRef);

        @Override
        public double getZ()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getZ(this.nativeRef);
        }
        private native double native_getZ(long _nativeRef);

        @Override
        public void add(Vec4 v)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_add(this.nativeRef, v);
        }
        private native void native_add(long _nativeRef, Vec4 v);

        @Override
        public void addScaledVector(Vec4 v)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_addScaledVector(this.nativeRef, v);
        }
        private native void native_addScaledVector(long _nativeRef, Vec4 v);

        @Override
        public void sub(Vec4 v)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_sub(this.nativeRef, v);
        }
        private native void native_sub(long _nativeRef, Vec4 v);

        @Override
        public void multiply(double i)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_multiply(this.nativeRef, i);
        }
        private native void native_multiply(long _nativeRef, double i);

        @Override
        public void divide(double i)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_divide(this.nativeRef, i);
        }
        private native void native_divide(long _nativeRef, double i);

        @Override
        public double squareLength()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_squareLength(this.nativeRef);
        }
        private native double native_squareLength(long _nativeRef);

        @Override
        public double getLength()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getLength(this.nativeRef);
        }
        private native double native_getLength(long _nativeRef);

        @Override
        public void setLength(double length)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setLength(this.nativeRef, length);
        }
        private native void native_setLength(long _nativeRef, double length);

        @Override
        public Vec4 normalize()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_normalize(this.nativeRef);
        }
        private native Vec4 native_normalize(long _nativeRef);

        @Override
        public boolean isZero()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isZero(this.nativeRef);
        }
        private native boolean native_isZero(long _nativeRef);

        @Override
        public void set(double x, double y, double z, double w)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_set(this.nativeRef, x, y, z, w);
        }
        private native void native_set(long _nativeRef, double x, double y, double z, double w);

        @Override
        public double dot(Vec4 v)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_dot(this.nativeRef, v);
        }
        private native double native_dot(long _nativeRef, Vec4 v);

        @Override
        public Vec4 cross(Vec4 v)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_cross(this.nativeRef, v);
        }
        private native Vec4 native_cross(long _nativeRef, Vec4 v);

        @Override
        public double distance(Vec4 v)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_distance(this.nativeRef, v);
        }
        private native double native_distance(long _nativeRef, Vec4 v);

        @Override
        public void invert()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_invert(this.nativeRef);
        }
        private native void native_invert(long _nativeRef);

        public static native Vec4 create(double x, double y, double z);
    }
}
