// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace nok {

class AudioChannel;
class Sound;

class Audio {
public:
    virtual ~Audio() {}

    virtual int32_t get_samplesPerSecond() = 0;

    virtual std::shared_ptr<AudioChannel> stream(const std::shared_ptr<Sound> & sound, bool loop) = 0;
};

}  // namespace nok
