// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <memory>

namespace nok {

class Color {
public:
    virtual ~Color() {}

    static constexpr double BLACK = 4278190080;

    static constexpr float WHITE = 4294967295;

    static constexpr float RED = 4294901760;

    static constexpr float BLUE = 4278190335;

    static constexpr float GREEN = 4278255360;

    static constexpr float MAGENTA = 4294902015;

    static constexpr float YELLOW = 4294967040;

    static constexpr float CYAN = 4278255615;

    static constexpr float PURPLE = 4286578816;

    static constexpr float PINK = 4294951115;

    static constexpr float ORANGE = 4294944000;

    virtual float get_R() = 0;

    virtual float get_G() = 0;

    virtual float get_B() = 0;

    virtual float get_A() = 0;

    virtual void set_R(float r) = 0;

    virtual void set_G(float g) = 0;

    virtual void set_B(float b) = 0;

    virtual void set_A(float a) = 0;

    static std::shared_ptr<Color> create(double color);
};

}  // namespace nok
