// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#include "color.hpp"  // my header

namespace nok {

double constexpr Color::BLACK;

float constexpr Color::WHITE;

float constexpr Color::RED;

float constexpr Color::BLUE;

float constexpr Color::GREEN;

float constexpr Color::MAGENTA;

float constexpr Color::YELLOW;

float constexpr Color::CYAN;

float constexpr Color::PURPLE;

float constexpr Color::PINK;

float constexpr Color::ORANGE;

}  // namespace nok
