// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <memory>

namespace nok {

class Color {
public:
    virtual ~Color() {}

    static double const BLACK;

    static float const WHITE;

    static float const RED;

    static float const BLUE;

    static float const GREEN;

    static float const MAGENTA;

    static float const YELLOW;

    static float const CYAN;

    static float const PURPLE;

    static float const PINK;

    static float const ORANGE;

    virtual float get_R() = 0;

    virtual float get_G() = 0;

    virtual float get_B() = 0;

    virtual float get_A() = 0;

    virtual void set_R(float r) = 0;

    virtual void set_G(float g) = 0;

    virtual void set_B(float b) = 0;

    virtual void set_A(float a) = 0;

    static std::shared_ptr<Color> create(double color);
};

}  // namespace nok
