// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <functional>

namespace nok {

enum class CullMode : int {
    CLOCKWISE,
    COUNTERCLOCKWISE,
    NOCULLING,
};

}  // namespace nok

namespace std {

template <>
struct hash<::nok::CullMode> {
    size_t operator()(::nok::CullMode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
