// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <functional>

namespace nok {

enum class FogType : int {
    LINEARFOG,
};

}  // namespace nok

namespace std {

template <>
struct hash<::nok::FogType> {
    size_t operator()(::nok::FogType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
