// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <functional>

namespace nok {

enum class ImageScaleQuality : int {
    LOW,
    HIGH,
};

}  // namespace nok

namespace std {

template <>
struct hash<::nok::ImageScaleQuality> {
    size_t operator()(::nok::ImageScaleQuality type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
