// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

namespace nok {

class IndexBuffer {
public:
    virtual ~IndexBuffer() {}

    static std::shared_ptr<IndexBuffer> create(int32_t count);

    virtual std::vector<int32_t> lock() = 0;

    virtual void unlock() = 0;

    virtual int32_t count() = 0;
};

}  // namespace nok
