// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#include "mat2x3_module.hpp"  // my header

namespace nok {

double const Mat2x3Module::WIDTH = 2;

double const Mat2x3Module::HEIGHT = 3;

}  // namespace nok
