// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#include "mat2x4_module.hpp"  // my header

namespace nok {

double const Mat2x4Module::WIDTH = 2;

double const Mat2x4Module::HEIGHT = 4;

}  // namespace nok
