// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#include "mat3.hpp"  // my header

namespace nok {

float const Mat3::WIDTH = 3;

float const Mat3::HEIGHT = 3;

}  // namespace nok
