// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#include "mat3x2_module.hpp"  // my header

namespace nok {

double const Mat3x2Module::WIDTH = 3;

double const Mat3x2Module::HEIGHT = 2;

}  // namespace nok
