// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from system.djinni

#pragma once

#include <functional>

namespace nok {

enum class Orientation : int {
    ORIENTATIONLANDSCAPELEFT,
    ORIENTATIONLANDSCAPERIGHT,
    ORIENTATIONPORTRAIT,
    ORIENTATIONPORTRAITUPSIDEDOWN,
    ORIENTATIONUNKNOWN,
};

}  // namespace nok

namespace std {

template <>
struct hash<::nok::Orientation> {
    size_t operator()(::nok::Orientation type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
