// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

namespace nok {

class AudioChannel;

class ResamplingAudioChannel {
public:
    virtual ~ResamplingAudioChannel() {}

    virtual std::vector<float> get_data() = 0;

    virtual int32_t get_samplesRate() = 0;

    static std::shared_ptr<AudioChannel> create(bool looping, int32_t sampleRate);

    virtual float sample(int32_t position, int32_t sampleRate) = 0;

    virtual void lerp(float v0, float v1, float t) = 0;

    virtual int32_t sampleLength(int32_t sampleRate) = 0;

    virtual void nextSamples(const std::vector<float> & requestedSamples, int32_t requestedLength, int32_t sampleRate) = 0;

    virtual void play() = 0;

    virtual void pause() = 0;

    virtual void stop() = 0;

    virtual float get_length() = 0;

    virtual float get_position() = 0;

    virtual void set_position(float pos) = 0;

    virtual float get_volume() = 0;

    virtual void set_volume(float vol) = 0;

    virtual bool get_finished() = 0;

    virtual void max(int32_t a, int32_t b) = 0;

    virtual void min(int32_t a, int32_t b) = 0;
};

}  // namespace nok
