// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

namespace nok {

class Sound {
public:
    virtual ~Sound() {}

    virtual std::vector<uint8_t> get_compressedData() = 0;

    virtual std::vector<float> get_uncompressedData() = 0;

    virtual float get_length() = 0;

    virtual int32_t get_channels() = 0;

    virtual int32_t get_sampleRate() = 0;

    virtual void set_compressedData(const std::vector<uint8_t> & b) = 0;

    virtual void set_uncompressedData(const std::vector<float> & d) = 0;

    virtual void set_length(float length) = 0;

    virtual void set_channels(int32_t channels) = 0;

    virtual void set_sampleRate(int32_t rate) = 0;

    virtual void unload() = 0;

    static std::shared_ptr<Sound> create();
};

}  // namespace nok
