// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from system.djinni

#pragma once

#include <cstdint>

namespace nok {

class System {
public:
    virtual ~System() {}

    virtual void init(int32_t width, int32_t height) = 0;

    virtual void start() = 0;

    virtual bool frame() = 0;

    virtual void stop() = 0;
};

}  // namespace nok
