// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <functional>

namespace nok {

enum class TextureAddressing : int {
    REPEAT,
    MIRROR,
    CLAMP,
    BORDER,
};

}  // namespace nok

namespace std {

template <>
struct hash<::nok::TextureAddressing> {
    size_t operator()(::nok::TextureAddressing type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
