// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <vector>

namespace nok {

class Image;

class TextureArray {
public:
    virtual ~TextureArray() {}

    static std::shared_ptr<TextureArray> create(const std::vector<std::shared_ptr<Image>> & image, int32_t count);
};

}  // namespace nok
