// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace nok {

struct TextureUnit final {
    int32_t value;

    TextureUnit(int32_t value_)
    : value(std::move(value_))
    {}
};

}  // namespace nok
