// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <memory>
#include <string>

namespace nok {

enum class VertexAttribute;
enum class VertexData;

class VertexElement {
public:
    virtual ~VertexElement() {}

    virtual std::string get_name() = 0;

    virtual void set_name(const std::string & n) = 0;

    virtual VertexAttribute get_attribute() = 0;

    virtual void set_attribute(VertexAttribute a) = 0;

    virtual VertexData get_data() = 0;

    virtual void set_data(VertexData d) = 0;

    static std::shared_ptr<VertexElement> create();

    static std::shared_ptr<VertexElement> createWithName(const std::string & name, VertexData data);

    static std::shared_ptr<VertexElement> createWithAttribute(VertexAttribute attribute, VertexData data);
};

}  // namespace nok
