// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#pragma once

#include <functional>

namespace nok {

enum class ZCompareMode : int {
    ZCOMPAREALWAYS,
    ZCOMPARENEVER,
    ZCOMPAREEQUAL,
    ZCOMPARENOTEQUAL,
    ZCOMPARELESS,
    ZCOMPARELESSEQUAL,
    ZCOMPAREGREATER,
    ZCOMPAREGREATEREQUAL,
};

}  // namespace nok

namespace std {

template <>
struct hash<::nok::ZCompareMode> {
    size_t operator()(::nok::ZCompareMode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
