// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#import <Foundation/Foundation.h>
@class NOKAudioBuffer;
@class NOKAudioChannel;
@class NOKSound;


@interface NOKAudio : NSObject

- (int32_t)getSamplesPerSecond;

+ (nullable NOKAudioChannel *)stream:(nullable NOKSound *)sound
                                loop:(BOOL)loop;

+ (void)init;

+ (nullable NOKAudioBuffer *)getBuffer;

+ (void)setBuffer:(nullable NOKAudioBuffer *)buf;

+ (void)update;

+ (void)shutdown;

+ (float)readSample;

@end
