// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#include "audio.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKAudio;

namespace djinni_generated {

class Audio
{
public:
    using CppType = std::shared_ptr<::nok::Audio>;
    using CppOptType = std::shared_ptr<::nok::Audio>;
    using ObjcType = NOKAudio*;

    using Boxed = Audio;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

