// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import <Foundation/Foundation.h>

@interface NOKBakedChar : NSObject
- (nonnull instancetype)initWithX0:(int32_t)x0
                                y0:(int32_t)y0
                                x1:(int32_t)x1
                                x2:(int32_t)x2
                              xoff:(float)xoff
                              yoff:(float)yoff
                          xadvance:(float)xadvance;
+ (nonnull instancetype)bakedCharWithX0:(int32_t)x0
                                     y0:(int32_t)y0
                                     x1:(int32_t)x1
                                     x2:(int32_t)x2
                                   xoff:(float)xoff
                                   yoff:(float)yoff
                               xadvance:(float)xadvance;

@property (nonatomic, readonly) int32_t x0;

@property (nonatomic, readonly) int32_t y0;

@property (nonatomic, readonly) int32_t x1;

@property (nonatomic, readonly) int32_t x2;

@property (nonatomic, readonly) float xoff;

@property (nonatomic, readonly) float yoff;

@property (nonatomic, readonly) float xadvance;

@end
