// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import "NOKBakedChar.h"
#include "baked_char.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKBakedChar;

namespace djinni_generated {

struct BakedChar
{
    using CppType = ::nok::BakedChar;
    using ObjcType = NOKBakedChar*;

    using Boxed = BakedChar;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
