// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import "NOKConstantLocation.h"
#include "constant_location.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKConstantLocation;

namespace djinni_generated {

struct ConstantLocation
{
    using CppType = ::nok::ConstantLocation;
    using ObjcType = NOKConstantLocation*;

    using Boxed = ConstantLocation;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
