// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import "NOKConstantLocation+Private.h"
#include <cassert>

namespace djinni_generated {

auto ConstantLocation::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    (void)obj; // Suppress warnings in relase builds for empty records
    return {};
}

auto ConstantLocation::fromCpp(const CppType& cpp) -> ObjcType
{
    (void)cpp; // Suppress warnings in relase builds for empty records
    return [[NOKConstantLocation alloc] init];
}

}  // namespace djinni_generated
