// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import "NOKFontStyle.h"
#include "font_style.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKFontStyle;

namespace djinni_generated {

struct FontStyle
{
    using CppType = ::nok::FontStyle;
    using ObjcType = NOKFontStyle*;

    using Boxed = FontStyle;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
