// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import "NOKImageScaleQuality.h"
#import <Foundation/Foundation.h>
@class NOKGraphics2;
@class NOKKavur;
@class NOKMat3;
@class NOKMat4;
@class NOKPipelineState;
@class NOKRenderTarget;
@class NOKTexture;


@interface NOKGraphics2 : NSObject

+ (nullable NOKGraphics2 *)create:(int32_t)width
                           height:(int32_t)height
                         rTargets:(BOOL)rTargets;

- (void)pushRotation:(float)angle
             centerx:(float)centerx
             centery:(float)centery;

- (void)drawImage:(nullable NOKTexture *)img
                x:(float)x
                y:(float)y;

- (void)drawScaledSubImage:(nullable NOKTexture *)img
                        sx:(float)sx
                        sy:(float)sy
                        sw:(float)sw
                        sh:(float)sh
                        dx:(float)dx
                        dy:(float)dy
                        dw:(float)dw
                        dh:(float)dh;

- (void)drawImageRenderTarget:(nullable NOKRenderTarget *)img
                            x:(float)x
                            y:(float)y;

- (void)drawRect:(float)x
               y:(float)y
           width:(float)width
          height:(float)height
        strength:(float)strength;

- (void)fillRect:(float)x
               y:(float)y
           width:(float)width
          height:(float)height;

- (void)drawString:(nonnull NSString *)text
                 x:(float)x
                 y:(float)y;

- (void)drawLine:(float)x1
              y1:(float)y1
              x2:(float)x2
              y2:(float)y2
        strength:(float)strength;

- (void)fillTriangle:(float)x1
                  y1:(float)y1
                  x2:(float)x2
                  y2:(float)y2
                  x3:(float)x3
                  y3:(float)y3;

- (void)setPipeline:(nullable NOKPipelineState *)pip;

- (void)scissor:(int32_t)x
              y:(int32_t)y
          width:(int32_t)width
         height:(int32_t)height;

- (void)disableScissor;

- (nullable NOKMat3 *)getTransformation;

- (nullable NOKMat4 *)getProjectionMatrix;

- (nonnull NSArray<NSNumber *> *)getFontGlyphs;

- (void)begin:(BOOL)renderTargets
        width:(int32_t)width
       height:(int32_t)height
        clear:(BOOL)clear
   clearColor:(int32_t)clearColor;

- (void)clear:(int32_t)color;

- (void)flush;

- (void)end;

- (void)drawVideoInternal:(float)x
                        y:(float)y
                    width:(float)width
                   height:(float)height;

- (void)drawVideo:(float)x
                y:(float)y
            width:(float)width
           height:(float)height;

- (int32_t)getColor;

- (void)setColor:(float)color;

- (float)getOpacity;

- (void)setOpacity:(float)opacity;

- (NOKImageScaleQuality)getImageScaleQuality;

- (void)setImageScaleQuality:(NOKImageScaleQuality)value;

- (NOKImageScaleQuality)getMipmapScaleQuality;

- (void)setMipmapScaleQuality:(NOKImageScaleQuality)value;

- (nullable NOKKavur *)getFont;

- (int32_t)getFontSize;

- (void)setFontSize:(int32_t)value;

- (double)getFontColor;

- (void)setFontColor:(double)color;

@end
