// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import <Foundation/Foundation.h>
@class NOKIndexBuffer;


@interface NOKIndexBuffer : NSObject

+ (nullable NOKIndexBuffer *)create:(int32_t)count;

- (nonnull NSArray<NSNumber *> *)lock;

- (void)unlock;

- (int32_t)count;

@end
