// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NOKImageFormat)
{
    NOKImageFormatRGBA32,
    NOKImageFormatGREY8,
    NOKImageFormatRGB24,
    NOKImageFormatRGBA128,
    NOKImageFormatRGBA64,
    NOKImageFormatA32,
    NOKImageFormatBGRA32,
    NOKImageFormatA16,
};
