// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#include "kavur.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKKavur;

namespace djinni_generated {

class Kavur
{
public:
    using CppType = std::shared_ptr<::nok::Kavur>;
    using CppOptType = std::shared_ptr<::nok::Kavur>;
    using ObjcType = NOKKavur*;

    using Boxed = Kavur;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

