// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#include "mat2x4_module.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKMat2x4Module;

namespace djinni_generated {

class Mat2x4Module
{
public:
    using CppType = std::shared_ptr<::nok::Mat2x4Module>;
    using CppOptType = std::shared_ptr<::nok::Mat2x4Module>;
    using ObjcType = NOKMat2x4Module*;

    using Boxed = Mat2x4Module;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

