// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import "NOKMat3x2Module.h"


double const NOKMat3x2ModuleWidth = 3;

double const NOKMat3x2ModuleHeight = 2;
