// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import "NOKMat4x2Module.h"


double const NOKMat4x2ModuleWidth = 4;

double const NOKMat4x2ModuleHeight = 2;
