// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import "NOKMat3+Private.h"
#import "NOKMat3.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "NOKVec3i+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface NOKMat3 ()

- (id)initWithCpp:(const std::shared_ptr<::nok::Mat3>&)cppRef;

@end

@implementation NOKMat3 {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::nok::Mat3>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::nok::Mat3>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (float)get:(float)row
         col:(float)col {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->get(::djinni::F32::toCpp(row),
                                                       ::djinni::F32::toCpp(col));
        return ::djinni::F32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)set:(float)row
        col:(float)col
          v:(float)v {
    try {
        _cppRefHandle.get()->set(::djinni::F32::toCpp(row),
                                 ::djinni::F32::toCpp(col),
                                 ::djinni::F32::toCpp(v));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)orthogonalProjection:(float)left
                                     right:(float)right
                                    bottom:(float)bottom
                                       top:(float)top
                                        zn:(float)zn
                                        zf:(float)zf {
    try {
        auto objcpp_result_ = ::nok::Mat3::orthogonalProjection(::djinni::F32::toCpp(left),
                                                                ::djinni::F32::toCpp(right),
                                                                ::djinni::F32::toCpp(bottom),
                                                                ::djinni::F32::toCpp(top),
                                                                ::djinni::F32::toCpp(zn),
                                                                ::djinni::F32::toCpp(zf));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)perspective:(float)left
                            right:(float)right
                              top:(float)top
                           bottom:(float)bottom
                             near:(float)near
                              far:(float)far {
    try {
        auto objcpp_result_ = ::nok::Mat3::perspective(::djinni::F32::toCpp(left),
                                                       ::djinni::F32::toCpp(right),
                                                       ::djinni::F32::toCpp(top),
                                                       ::djinni::F32::toCpp(bottom),
                                                       ::djinni::F32::toCpp(near),
                                                       ::djinni::F32::toCpp(far));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)perspectiveFOV:(float)fov
                              aspect:(float)aspect
                                near:(float)near
                                 far:(float)far {
    try {
        auto objcpp_result_ = ::nok::Mat3::perspectiveFOV(::djinni::F32::toCpp(fov),
                                                          ::djinni::F32::toCpp(aspect),
                                                          ::djinni::F32::toCpp(near),
                                                          ::djinni::F32::toCpp(far));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)lookAt:(nullable NOKVec3i *)eye
                          at:(nullable NOKVec3i *)at
                          up:(nullable NOKVec3i *)up {
    try {
        auto objcpp_result_ = ::nok::Mat3::lookAt(::djinni_generated::Vec3i::toCpp(eye),
                                                  ::djinni_generated::Vec3i::toCpp(at),
                                                  ::djinni_generated::Vec3i::toCpp(up));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)lookAlong:(nullable NOKVec3i *)axis
                            eye:(nullable NOKVec3i *)eye
                             up:(nullable NOKVec3i *)up {
    try {
        auto objcpp_result_ = ::nok::Mat3::lookAlong(::djinni_generated::Vec3i::toCpp(axis),
                                                     ::djinni_generated::Vec3i::toCpp(eye),
                                                     ::djinni_generated::Vec3i::toCpp(up));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)translation:(float)x
                                y:(float)y {
    try {
        auto objcpp_result_ = ::nok::Mat3::translation(::djinni::F32::toCpp(x),
                                                       ::djinni::F32::toCpp(y));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)movement:(float)x
                             y:(float)y
                             z:(float)z {
    try {
        auto objcpp_result_ = ::nok::Mat3::movement(::djinni::F32::toCpp(x),
                                                    ::djinni::F32::toCpp(y),
                                                    ::djinni::F32::toCpp(z));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)identity {
    try {
        auto objcpp_result_ = ::nok::Mat3::identity();
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)scale:(float)scale {
    try {
        auto objcpp_result_ = ::nok::Mat3::scale(::djinni::F32::toCpp(scale));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)rotationX:(float)alpha {
    try {
        auto objcpp_result_ = ::nok::Mat3::rotationX(::djinni::F32::toCpp(alpha));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)rotationY:(float)alpha {
    try {
        auto objcpp_result_ = ::nok::Mat3::rotationY(::djinni::F32::toCpp(alpha));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)rotationZ:(float)alpha {
    try {
        auto objcpp_result_ = ::nok::Mat3::rotationZ(::djinni::F32::toCpp(alpha));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)rotation:(float)yaw
                         pitch:(float)pitch
                          roll:(float)roll {
    try {
        auto objcpp_result_ = ::nok::Mat3::rotation(::djinni::F32::toCpp(yaw),
                                                    ::djinni::F32::toCpp(pitch),
                                                    ::djinni::F32::toCpp(roll));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)create {
    try {
        auto objcpp_result_ = ::nok::Mat3::create();
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)from:(nullable NOKMat3 *)mat {
    try {
        auto objcpp_result_ = ::nok::Mat3::from(::djinni_generated::Mat3::toCpp(mat));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NOKMat3 *)add:(nullable NOKMat3 *)mat {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->add(::djinni_generated::Mat3::toCpp(mat));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NOKMat3 *)sub:(nullable NOKMat3 *)mat {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->sub(::djinni_generated::Mat3::toCpp(mat));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NOKMat3 *)multiply:(float)i {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->multiply(::djinni::F32::toCpp(i));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NOKMat3 *)clone {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->clone();
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NOKMat3 *)transpose {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->transpose();
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nullable NOKMat3 *)transpose3x3 {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->transpose3x3();
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (float)trace {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->trace();
        return ::djinni::F32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (float)determinant {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->determinant();
        return ::djinni::F32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nullable NOKMat3 *)linearInterpolate:(nullable NOKMat3 *)a
                                      b:(nullable NOKMat3 *)b
                                   prop:(float)prop {
    try {
        auto objcpp_result_ = ::nok::Mat3::linearInterpolate(::djinni_generated::Mat3::toCpp(a),
                                                             ::djinni_generated::Mat3::toCpp(b),
                                                             ::djinni::F32::toCpp(prop));
        return ::djinni_generated::Mat3::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}


namespace djinni_generated {

auto Mat3::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Mat3::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<NOKMat3>(cpp);
}

}  // namespace djinni_generated

@end
