// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from system.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NOKOrientation)
{
    NOKOrientationOrientationLandscapeLeft,
    NOKOrientationOrientationLandscapeRight,
    NOKOrientationOrientationPortrait,
    NOKOrientationOrientationPortraitUpsideDown,
    NOKOrientationOrientationUnknown,
};
