// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#include "pipeline_state.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKPipelineState;

namespace djinni_generated {

class PipelineState
{
public:
    using CppType = std::shared_ptr<::nok::PipelineState>;
    using CppOptType = std::shared_ptr<::nok::PipelineState>;
    using ObjcType = NOKPipelineState*;

    using Boxed = PipelineState;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

