// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import <Foundation/Foundation.h>
@class NOKMat4;
@class NOKQuaternion;
@class NOKVec3;


@interface NOKQuaternion : NSObject

+ (nullable NOKQuaternion *)create:(float)x
                                 y:(float)y
                                 z:(float)z
                                 w:(float)w;

+ (nullable NOKQuaternion *)fromAxis:(nullable NOKVec3 *)axis
                              radian:(float)radian;

- (nullable NOKQuaternion *)slerp:(float)t
                                q:(nullable NOKQuaternion *)q;

- (nullable NOKQuaternion *)rotated:(nullable NOKQuaternion *)b;

- (nullable NOKQuaternion *)scaled:(float)scale;

- (float)dot:(nullable NOKQuaternion *)q;

- (nullable NOKMat4 *)matrix;

- (nullable NOKQuaternion *)add:(nullable NOKQuaternion *)q;

- (nullable NOKQuaternion *)sub:(nullable NOKQuaternion *)q;

- (nullable NOKQuaternion *)addVec3:(nullable NOKVec3 *)v;

- (nullable NOKQuaternion *)multiply:(nullable NOKQuaternion *)q;

- (void)normalize;

- (void)rotate:(nullable NOKQuaternion *)q;

- (nullable NOKQuaternion *)conjugate;

- (nullable NOKQuaternion *)invert;

- (float)getX;

- (float)getY;

- (float)getZ;

- (void)setX:(float)x;

- (void)setY:(float)y;

- (void)setZ:(float)z;

@end
