// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from system.djinni

#import "NOKSystem+Private.h"
#import "NOKSystem.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface NOKSystem ()

- (id)initWithCpp:(const std::shared_ptr<::nok::System>&)cppRef;

@end

@implementation NOKSystem {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::nok::System>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::nok::System>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)init:(int32_t)width
      height:(int32_t)height {
    try {
        _cppRefHandle.get()->init(::djinni::I32::toCpp(width),
                                  ::djinni::I32::toCpp(height));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)start {
    try {
        _cppRefHandle.get()->start();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)frame {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->frame();
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)stop {
    try {
        _cppRefHandle.get()->stop();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto System::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto System::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<NOKSystem>(cpp);
}

}  // namespace djinni_generated

@end
