// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#include "shader.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKShader;

namespace djinni_generated {

class Shader
{
public:
    using CppType = std::shared_ptr<::nok::Shader>;
    using CppOptType = std::shared_ptr<::nok::Shader>;
    using ObjcType = NOKShader*;

    using Boxed = Shader;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

