// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from audio.djinni

#import <Foundation/Foundation.h>
@class NOKSound;


@interface NOKSound : NSObject

- (nonnull NSData *)getCompressedData;

- (nonnull NSArray<NSNumber *> *)getUncompressedData;

- (float)getLength;

- (int32_t)getChannels;

- (int32_t)getSampleRate;

- (void)setCompressedData:(nonnull NSData *)b;

- (void)setUncompressedData:(nonnull NSArray<NSNumber *> *)d;

- (void)setLength:(float)length;

- (void)setChannels:(int32_t)channels;

- (void)setSampleRate:(int32_t)rate;

- (void)unload;

+ (nullable NOKSound *)create;

@end
