// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from system.djinni

#include "system.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKSystem;

namespace djinni_generated {

class System
{
public:
    using CppType = std::shared_ptr<::nok::System>;
    using CppOptType = std::shared_ptr<::nok::System>;
    using ObjcType = NOKSystem*;

    using Boxed = System;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

