// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import <Foundation/Foundation.h>
@class NOKImage;
@class NOKTextureArray;


@interface NOKTextureArray : NSObject

+ (nullable NOKTextureArray *)create:(nonnull NSArray<NOKImage *> *)image
                               count:(int32_t)count;

@end
