// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nok.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, NOKVertexAttribute)
{
    NOKVertexAttributeNoVertexAttribute,
    NOKVertexAttributeVertexCoord,
    NOKVertexAttributeVertexNormal,
    NOKVertexAttributeVertexColor0,
    NOKVertexAttributeVertexColor1,
    NOKVertexAttributeVertexTexCoord0,
    NOKVertexAttributeVertexTexCoord1,
    NOKVertexAttributeVertexTexCoord2,
    NOKVertexAttributeVertexTexCoord3,
    NOKVertexAttributeVertexTexCoord4,
    NOKVertexAttributeVertexTexCoord5,
    NOKVertexAttributeVertexTexCoord6,
    NOKVertexAttributeVertexTexCoord7,
};
