// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import <Foundation/Foundation.h>
@class NOKVec2i;


@interface NOKVec2i : NSObject

- (int32_t)getX;

- (int32_t)getY;

- (void)setX:(int32_t)x;

- (void)setY:(int32_t)y;

- (void)add:(nullable NOKVec2i *)v;

- (void)addScaledVector:(nullable NOKVec2i *)v;

- (void)sub:(nullable NOKVec2i *)v;

- (void)multiply:(int32_t)i;

- (void)divide:(int32_t)i;

- (int32_t)squareLength;

- (int32_t)getLength;

- (void)setLength:(int32_t)length;

- (nullable NOKVec2i *)normalize;

- (BOOL)isZero;

- (int32_t)get:(int32_t)i;

- (void)set:(int32_t)i
          v:(int32_t)v;

- (int32_t)dot:(nullable NOKVec2i *)v;

- (nullable NOKVec2i *)cross:(nullable NOKVec2i *)v;

- (int32_t)distance:(nullable NOKVec2i *)v;

+ (nullable NOKVec2i *)create:(int32_t)x
                            y:(int32_t)y;

@end
