// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import <Foundation/Foundation.h>
@class NOKVec4;


@interface NOKVec4 : NSObject

- (double)getX;

- (double)getY;

- (double)getZ;

- (double)getW;

- (void)add:(nullable NOKVec4 *)v;

- (void)addScaledVector:(nullable NOKVec4 *)v;

- (void)sub:(nullable NOKVec4 *)v;

- (void)multiply:(double)i;

- (void)divide:(double)i;

- (double)squareLength;

- (double)getLength;

- (void)setLength:(double)length;

- (nullable NOKVec4 *)normalize;

- (BOOL)isZero;

- (void)set:(double)x
          y:(double)y
          z:(double)z
          w:(double)w;

- (double)dot:(nullable NOKVec4 *)v;

- (nullable NOKVec4 *)cross:(nullable NOKVec4 *)v;

- (double)distance:(nullable NOKVec4 *)v;

- (void)invert;

+ (nullable NOKVec4 *)create:(double)x
                           y:(double)y
                           z:(double)z;

@end
