// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import <Foundation/Foundation.h>
@class NOKVec3;


@interface NOKVec3 : NSObject

- (double)getX;

- (double)getY;

- (double)getZ;

- (void)add:(nullable NOKVec3 *)v;

- (void)addScaledVector:(nullable NOKVec3 *)v;

- (void)sub:(nullable NOKVec3 *)v;

- (void)multiply:(double)i;

- (void)divide:(double)i;

- (double)squareLength;

- (double)getLength;

- (void)setLength:(double)length;

- (nullable NOKVec3 *)normalize;

- (BOOL)isZero;

- (nullable NOKVec3 *)getXyz;

- (void)set:(double)x
          y:(double)y
          z:(double)z;

- (double)dot:(nullable NOKVec3 *)v;

- (nullable NOKVec3 *)cross:(nullable NOKVec3 *)v;

- (double)distance:(nullable NOKVec3 *)v;

- (void)invert;

+ (nullable NOKVec3 *)create:(double)x
                           y:(double)y
                           z:(double)z;

@end
