// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#import <Foundation/Foundation.h>
@class NOKVec2;


@interface NOKVec2 : NSObject

- (float)getX;

- (float)getY;

- (void)setX:(float)x;

- (void)setY:(float)y;

- (void)add:(nullable NOKVec2 *)v;

- (void)addScaledVector:(nullable NOKVec2 *)v;

- (void)sub:(nullable NOKVec2 *)v;

- (void)multiply:(float)i;

- (void)divide:(float)i;

- (float)squareLength;

- (float)getLength;

- (void)setLength:(float)length;

- (nullable NOKVec2 *)normalize;

- (BOOL)isZero;

- (float)get:(float)i;

- (void)set:(float)i
          v:(float)v;

- (float)dot:(nullable NOKVec2 *)v;

- (nullable NOKVec2 *)cross:(nullable NOKVec2 *)v;

- (float)distance:(nullable NOKVec2 *)v;

+ (nullable NOKVec2 *)create:(float)x
                           y:(float)y;

@end
