// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from math.djinni

#include "vec4i.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class NOKVec4i;

namespace djinni_generated {

class Vec4i
{
public:
    using CppType = std::shared_ptr<::nok::Vec4i>;
    using CppOptType = std::shared_ptr<::nok::Vec4i>;
    using ObjcType = NOKVec4i*;

    using Boxed = Vec4i;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

